name: Build and run
on: push

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        run: make
      - name: Run application
        run: ./main
