name: Build
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run application
        run: make
      - name: Run application
        run: ./main
